/* ratio = poster aspect ratio ("4/5", "1/1", "16/9"...) so the frame fits it exactly.
   King Penthouse — event collection (single source of truth).
   To add an event: copy a block, fill the fields, create a page file
   named after `url`, and it appears on the Events page automatically.
   status: "active" | "hidden"   ·   past dates drop off automatically. */
window.KP_STD_DETAILS = window.KP_STD_DETAILS || [
  { title: "What to expect", body: "King Penthouse is a private warehouse event space located minutes from Pearson Airport.\n\nThe night starts at 10:30 PM and runs until 4 AM.\n\nIf you\u2019ve been to lifestyle parties before, you already know the room usually changes as the night gets later. Come early to socialize and get comfortable, or come later when things are in full swing.\n\nYou are welcome to come to meet people, dance, flirt, explore, play, or just enjoy the atmosphere. There is never any obligation to participate in anything." },
  { title: "Single men", body: "Single men are welcome at this event, but attendance is approved.\n\nWe try to keep the guest mix balanced and comfortable for everyone, so simply marking yourself as \u201cgoing\u201d does not automatically guarantee entry.\n\nIf you are attending as a single male, please message us for verification and wait for confirmation." },
  { title: "Couples & single women", body: "Couples are welcome.\n\nSingle women attend free and are given priority parking directly in front of the entrance so they do not have to walk farther alone at night." },
  { title: "Consent", body: "Consent is mandatory at King Penthouse.\n\nAlways ask before touching someone, joining play, or assuming interest. Being at a play party does not mean someone is available to you.\n\nA yes to one thing is not a yes to everything, and anyone can change their mind at any time. Respect a no the first time.\n\nAnyone who repeatedly pushes boundaries or makes other guests uncomfortable will be removed." },
  { title: "Privacy", body: "No photos or videos of guests without their explicit permission.\n\nWe take guest privacy seriously and expect the same from everyone who attends." },
  { title: "The space", body: "There are areas for socializing as well as separate play areas.\n\nLockers/storage are available for personal belongings, but they do not lock, so please leave valuables at home or secured in your vehicle.\n\nFeel free to bring anything you may personally need for the night, including a change of clothes or towel." },
  { title: "Verification & address", body: "King Penthouse events are private and the exact address is not posted publicly.\n\nGuests must complete our verification process before receiving event information. Once confirmed, the address and arrival instructions will be sent directly to you." },
  { title: "House rules", body: "Consent first.\nNo pressure.\nNo photos or videos without permission.\nRespect other guests.\nRespect the venue.\nMaintain good hygiene.\nClean up after yourself.\nPlay is never guaranteed." }
];
window.KP_EVENTS = [
  {
    slug: "aug29-all-girl",
    category: "Lesbian/All Girl",
    url: "Aug29-All-Girl.html",
    name: "ALL GIRL PLAY PARTY",
    tagline: "EXCLUSIVELY FOR CIS WOMEN",
    date: "2026-08-29",
    dateLabel: "Saturday, August 29, 2026",
    time: "4:00 PM – 8:00 PM",
    prices: ["$30"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/08/29/king-penthouse-all-girl-play-party-klejbd",
    doublelist: "",
    ratio: "2/3",
    posterSrc: "./Aug29-All-Girl.webp",
    poster: "kp-poster-aug29-all-girl",
    status: "active"
  },
  {
    slug: "aug29-bbc-orgy",
    category: "BBC",
    url: "Aug29-BBC-Orgy.html",
    name: "BBC ORGY",
    tagline: "",
    date: "2026-08-29",
    dateLabel: "Saturday, August 29, 2026",
    time: "9:00 PM – 4:00 AM",
    prices: ["Single Males — $60", "Couples — $40", "Single Females — Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/08/29/king-penthouse-presents-bbc-orgy-p07mwg",
    doublelist: "",
    ratio: "2/3",
    posterSrc: "./Aug29-BBC-Orgy.webp",
    poster: "kp-poster-aug29-bbc-orgy",
    status: "hidden"
  },
  {
    slug: "aug30-genderfluid",
    category: "Fluid",
    url: "Aug30-Genderfluid.html",
    name: "GENDERFLUID AFTER DARK",
    tagline: "NO LABELS. JUST VIBES.",
    date: "2026-08-30",
    dateLabel: "Sunday, August 30, 2026",
    time: "9:00 PM – 2:00 AM",
    prices: ["$60 for everyone"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/08/30/king-penthouse-presents-genderfluid-after-dark-jgvnea",
    doublelist: "",
    ratio: "2/3",
    posterSrc: "./Aug30-Genderfluid.webp",
    poster: "kp-poster-aug30-genderfluid",
    status: "hidden"
  },
  {
    slug: "sep5-labor-day-bbc",
    category: "BBC",
    url: "Sep5-Labor-Day-BBC.html",
    name: "LABOUR DAY BBC ORGY",
    tagline: "GOING LATE FOR THE LONG WEEKEND",
    intro: "Labour Day weekend is one of the biggest party weekends of the year, so we\u2019re keeping King Penthouse open late Saturday night.",
    date: "2026-09-05",
    dateLabel: "Saturday, September 5, 2026",
    time: "10:30 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/09/05/labour-day-bbc-orgy-kbjk1l",
    doublelist: "",
    ratio: "2/3",
    details: [
      { title: "What to expect", body: "King Penthouse is a private warehouse event space located minutes from Pearson Airport.\n\nThe night starts at 10:30 PM and runs until 4 AM.\n\nIf you\u2019ve been to lifestyle parties before, you already know the room usually changes as the night gets later. Come early to socialize and get comfortable, or come later when things are in full swing.\n\nYou are welcome to come to meet people, dance, flirt, explore, play, or just enjoy the atmosphere. There is never any obligation to participate in anything." },
      { title: "Single men", body: "Single men are welcome at this event, but attendance is approved.\n\nWe try to keep the guest mix balanced and comfortable for everyone, so simply marking yourself as \u201cgoing\u201d does not automatically guarantee entry.\n\nIf you are attending as a single male, please message us for verification and wait for confirmation." },
      { title: "Couples & single women", body: "Couples are welcome.\n\nSingle women attend free and are given priority parking directly in front of the entrance so they do not have to walk farther alone at night." },
      { title: "Consent", body: "Consent is mandatory at King Penthouse.\n\nAlways ask before touching someone, joining play, or assuming interest. Being at a play party does not mean someone is available to you.\n\nA yes to one thing is not a yes to everything, and anyone can change their mind at any time. Respect a no the first time.\n\nAnyone who repeatedly pushes boundaries or makes other guests uncomfortable will be removed." },
      { title: "Privacy", body: "No photos or videos of guests without their explicit permission.\n\nWe take guest privacy seriously and expect the same from everyone who attends." },
      { title: "The space", body: "There are areas for socializing as well as separate play areas.\n\nLockers/storage are available for personal belongings, but they do not lock, so please leave valuables at home or secured in your vehicle.\n\nFeel free to bring anything you may personally need for the night, including a change of clothes or towel." },
          { title: "Verification & address", body: "King Penthouse events are private and the exact address is not posted publicly.\n\nGuests must complete our verification process before receiving event information. Once confirmed, the address and arrival instructions will be sent directly to you." },
      { title: "House rules", body: "Consent first.\nNo pressure.\nNo photos or videos without permission.\nRespect other guests.\nRespect the venue.\nMaintain good hygiene.\nClean up after yourself.\nPlay is never guaranteed." }
    ],
    posterSrc: "./Sep5-Labor-Day-BBC.webp",
    poster: "kp-poster-sep5-labor-day-bbc",
    status: "active"
  },
  {
    slug: "sep12-saturday-orgy",
    category: "Orgy",
    url: "Sep12-Saturday-Orgy.html",
    name: "SATURDAY ORGY",
    tagline: "WAREHOUSE / LOFT PARTY",
    intro: "Our signature Saturday night at King Penthouse \u2014 low light and a full house from 10:30 PM until 4 AM.",
    date: "2026-09-12",
    dateLabel: "Saturday, September 12, 2026",
    time: "10:30 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/09/12/king-penthouse-saturday-night-orgy-vzolo5",
    doublelist: "",
    ratio: "2/3",
    details: window.KP_STD_DETAILS,
    posterSrc: "./Sep12-Saturday-Orgy.webp",
    poster: "kp-poster-sep12-saturday-orgy",
    status: "active"
  },
  {
    slug: "sep19-caribbean-orgy",
    category: "Orgy",
    url: "Sep19-Caribbean-Orgy.html",
    name: "CARIBBEAN ORGY",
    tagline: "REGGAE \u00B7 SOCA \u00B7 DANCEHALL",
    intro: "A Caribbean-themed warehouse/loft party \u2014 reggae, soca and dancehall all night long.",
    date: "2026-09-19",
    dateLabel: "Saturday, September 19, 2026",
    time: "10:30 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/09/19/king-penthouse-caribbean-orgy-eayobf",
    doublelist: "",
    ratio: "1100/1454",
    details: window.KP_STD_DETAILS,
    posterSrc: "./Sep19-Caribbean-Orgy.webp",
    poster: "kp-poster-sep19-caribbean-orgy",
    status: "active"
  },
  {
    slug: "sep26-cowboy-bbc-orgy",
    category: "BBC",
    url: "Sep26-Cowboy-BBC.html",
    name: "BBC ORGY \u2014 SAVE A HORSE, RIDE A COWBOY",
    tagline: "NASHVILLE VIBES",
    intro: "Boots, hats and Nashville vibes. Message us to get verified before the night.",
    date: "2026-09-26",
    dateLabel: "Saturday, September 26, 2026",
    time: "10:30 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Exact address is provided to confirmed guests.",
    fetlife: "https://fetlife.com/events/2026/09/26/king-penthouse-save-a-horse-ride-a-cowboy-bbc-orgy-ivmqcn",
    doublelist: "",
    ratio: "2/3",
    details: window.KP_STD_DETAILS,
    posterSrc: "./Sep26-Cowboy-BBC.webp",
    poster: "kp-poster-sep26-cowboy-bbc-orgy",
    status: "active"
  },
  {
    slug: "oct3-king-of-spades",
    category: "BBC",
    url: "Oct3-King-Of-Spades.html",
    name: "BBC KING OF SPADES",
    tagline: "CALLING ALL QUEENS OF SPADES",
    intro: "It\u2019s time to appreciate the Kings. This Saturday, King Penthouse is flipping the spotlight onto the men for King of Spades \u2014 a BBC-focused night for the Queens who know exactly what they came for. If BBC is your thing, this is your Saturday.",
    date: "2026-10-03",
    dateLabel: "Saturday, October 3, 2026",
    time: "10:00 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Address given to approved guests. Cash or e-transfer at the door.",
    fetlife: "https://fetlife.com/events/2026/10/03/king-penthouse-bbc-king-of-spades-fdpbmj",
    doublelist: "",
    ratio: "2/3",
    details: [
      { title: "Calling all Queens", body: "Queens of Spades, BBC admirers, curious women, couples, and approved single men are invited to join us for a night where the Kings take center stage.\n\nYou\u2019ve seen the Queen of Spades. This time, we\u2019re crowning the King.\n\nCome meet the men, socialize, flirt, watch, explore, and show some appreciation for the Kings of KP.\n\nAlready a proud Queen of Spades? Come represent. Curious about the BBC/QoS scene but haven\u2019t explored it before? You\u2019re welcome too. Nobody needs to identify as a Queen of Spades to attend or participate.\n\nThe theme might be bold, but the same KP rule always applies: chemistry decides what happens next." },
      { title: "BBC night at King Penthouse", body: "Expect a sexually open, adults-only environment with BBC at the center of the night\u2019s theme.\n\nCome to socialize, meet people, watch, flirt, explore, or play where there is mutual interest.\n\nParticipation is always optional. Admission never guarantees play or access to another guest." },
      { title: "Admission", body: "Single Men: $60\nCouples: $40\nSingle Women: FREE\n\nCash or e-transfer at the door.\n\nSingle men must be verified and approved before attending. No unverified walk-ins." },
      { title: "Verification required", body: "New to King Penthouse? Message us before attending.\n\nPlease include your age, whether you\u2019re attending as a single man, single woman, or couple, a clear recent photo, and your FetLife profile/name if available.\n\nCouples should verify together." },
      { title: "Consent is everything", body: "The theme does not imply consent.\n\nNo one owes anyone attention, touching, play, or participation because of how they identify, what they\u2019re wearing, or why they came.\n\nAsk first. Respect boundaries. Take rejection gracefully.\n\nIf someone says no, hesitates, or changes their mind, stop." },
      { title: "Privacy", body: "No photos or videos in the main party area.\n\nGeneral phone use should remain in the designated entrance area. Anyone photographing or recording another guest without permission may be removed and banned.\n\nWhat happens at KP stays at KP." },
      { title: "Parking", body: "Single women: Parking directly in front of the venue.\n\nCouples & single men: Designated parking across the street.\n\nFull arrival information is provided after verification." }
    ],
    posterSrc: "./Oct3-King-Of-Spades.webp",
    poster: "kp-poster-oct3-king-of-spades",
    status: "active"
  },
  {
    slug: "oct10-bbcs-bikers-baddies",
    category: "BBC",
    url: "Oct10-BBCs-Bikers-Baddies.html",
    name: "BBCs, BIKERS & TATTOOED BADDIES",
    tagline: "GET YOUR TITTIES TATTED BEFORE MIDNIGHT",
    intro: "Ladies, get there before midnight. Pretty temporary tattoo designs \u2014 detailed mandalas, florals and ornamental pieces \u2014 for the girls who want them. Then the night belongs to the BBCs, the bikers and the tattooed baddies.",
    date: "2026-10-10",
    dateLabel: "Saturday, October 10, 2026",
    time: "10:30 PM \u2013 4:00 AM",
    prices: ["Single Males \u2014 $60", "Couples \u2014 $40", "Single Females \u2014 Free"],
    location: "Minutes from Pearson Airport",
    city: "Mississauga, Ontario",
    note: "Address given privately to confirmed guests.",
    fetlife: "",
    doublelist: "",
    ratio: "1152/1712",
    details: [
      { title: "Get your titties tatted before midnight", image: "./Oct10-Tattoo.webp", ratio: "1024/1536", body: "We\u2019ll have pretty temporary tattoo designs available for the girls who want them, including detailed mandalas, florals and ornamental designs that can be placed over your titties, around your nipples, or even over your pussy if you\u2019re feeling bold.\n\nNot permanent tattoos.\n\nThe tattoo setup is only happening before midnight, so don\u2019t be the one arriving at 1 AM asking where the titty tattoos went." },
      { title: "The night", body: "Expect the usual King Penthouse mix of music, flirting, socializing and play as the night gets later.\n\nCome with somebody or come alone. Come to meet people, watch the room develop, flirt, play if the chemistry is there, or just enjoy the party.\n\nThere is never any obligation to participate in anything simply because you came to a play event." },
      { title: "Admission", body: "Single Males: $60\nCouples: $40\nSingle Females: FREE" },
      { title: "Consent & house rules", body: "Ask before touching. A yes to one thing is not a yes to everything. Being naked, dressed provocatively, wearing an intimate tattoo, or being at King Penthouse is never automatic consent.\n\nRespect people\u2019s boundaries, privacy and personal space. No photos or videos of guests without their explicit permission. Anyone who repeatedly ignores boundaries will be asked to leave.\n\nThe exact private address and arrival information are provided to confirmed guests." }
    ],
    posterSrc: "./Oct10-BBCs-Bikers-Baddies.webp",
    poster: "kp-poster-oct10-bbcs-bikers-baddies",
    status: "active"
  }
];
